### ISSUE TITLE
microstack add-compute failed 

### ISSUE THREAD

**Issue by hugh712** [CanonicalLtd/microstack#96]
[Summary]
Follow the pate [0] to add compute node, but got bellow error:

```
$ sudo microstack init --auto --compute --join <my-connection-string>
2023-03-11 20:28:43,185 - microstack_init - INFO - Configuring clustering ...
2023-03-11 20:28:43,381 - microstack_init - INFO - Setting up as a compute node.
2023-03-11 20:28:47,272 - microstack_init - INFO - TLS certificates must be provided: config.tls.cacert-path, config.tls.cert-path, and config.tls.key-path.
2023-03-11 20:28:48,636 - microstack_init - INFO - Configuring networking ...
2023-03-11 20:28:52,861 - microstack_init - INFO - Opening horizon dashboard up to *
2023-03-11 20:28:53,678 - microstack_init - INFO - Disabling local rabbit ...
2023-03-11 20:28:57,712 - microstack_init - INFO - Disabling local MySQL ...
2023-03-11 20:29:01,264 - microstack_init - INFO - Disabling the Placement service...
2023-03-11 20:29:37,082 - microstack_init - INFO - Disabling nova control plane services ...
2023-03-11 20:29:40,292 - microstack_init - INFO - Configuring nova compute hypervisor ...
2023-03-11 20:29:40,292 - microstack_init - INFO - Checking virtualization extensions presence on the host
2023-03-11 20:29:40,318 - microstack_init - INFO - Hardware virtualization is supported - KVM will be used for Nova instances
2023-03-11 20:29:42,665 - microstack_init - INFO - Configuring the Spice HTML5 console service...
2023-03-11 20:29:59,544 - microstack_init - INFO - Creating security group rules ...
Bad Gateway (HTTP 502)
Traceback (most recent call last):
  File "/snap/microstack/245/bin/microstack", line 11, in <module>
    load_entry_point('microstack==0.0.1', 'console_scripts', 'microstack')()
  File "/snap/microstack/245/lib/python3.8/site-packages/microstack/main.py", line 44, in main
    cmd()
  File "/snap/microstack/245/lib/python3.8/site-packages/init/main.py", line 60, in wrapper
    return func(*args, **kwargs)
  File "/snap/microstack/245/lib/python3.8/site-packages/init/main.py", line 228, in init
    question.ask()
  File "/snap/microstack/245/lib/python3.8/site-packages/init/questions/question.py", line 210, in ask
    self.yes(awr)
  File "/snap/microstack/245/lib/python3.8/site-packages/init/questions/__init__.py", line 1011, in yes
    group_id = check_output('openstack', 'security', 'group', 'list',
  File "/snap/microstack/245/lib/python3.8/site-packages/init/shell.py", line 81, in check_output
    return subprocess.check_output(args, env=env,
  File "/usr/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '('openstack', 'security', 'group', 'list', '--project', 'admin', '-f', 'value', '-c', 'ID')' returned non-zero exit status 1.
```

[How to reproduce]
- Follow the page [0] to setup the enviroment
- Until this line "sudo microstack init --auto --compute --join <connection-string>"

[Extra Information]
OS version: Stock Ubuntu 20.04
Kernel version:  5.15.0-67-generic
Microstack version:  microstack         ussuri            245    latest/beta

[0] https://microstack.run/docs/multi-node

**Comment by hugh712** [comment]
hmmm, seems the compute node needs to be created on another machine,
is so, this is not a bug apparently, please help to close this issue.
